# Generated by Django 5.2.1 on 2025-08-15 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('goals', models.TextField(blank=True)),
                ('exercise_plans', models.ManyToManyField(blank=True, limit_choices_to={'category__slug': 'exercise'}, related_name='exercise_profiles', to='catalog.product')),
                ('nutrition_plans', models.ManyToManyField(blank=True, limit_choices_to={'category__slug': 'nutrition'}, related_name='nutrition_profiles', to='catalog.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
